// <auto-generated />
using System;
using AssignmentAdminEmployees.Infrastruct.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AssignmentAdminEmployees.Infrastruct.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AssignmentAdminEmployees.Domain.Moduls.DEPARTMENT", b =>
                {
                    b.Property<decimal>("DEPARTMENT_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DEPARTMENT_DESC")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("DEPARTMENT_ID");

                    b.ToTable("DEPARTMENT");
                });

            modelBuilder.Entity("AssignmentAdminEmployees.Domain.Moduls.EMPLOYEE", b =>
                {
                    b.Property<decimal>("EMPLOYEE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AGE")
                        .HasColumnType("int");

                    b.Property<decimal?>("DATETIMEADD")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DATETIMEMODDEL")
                        .HasColumnType("numeric");

                    b.Property<string>("EMAIL_ADDRERSS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EMPLOYEE_DEPARTMENT_ID")
                        .HasColumnType("numeric");

                    b.Property<string>("EMPLOYEE_NAME_LANG1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMPLOYEE_NAME_LANG2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EMPLOYEE_STATUS_ID")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("GENDER_ID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MOBILE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RECORDSTATUS")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SALARY")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("USER_ADD")
                        .HasColumnType("numeric");

                    b.Property<string>("WORKING_HOUR_FROM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WORKING_HOUR_TO")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EMPLOYEE_ID");

                    b.ToTable("EMPLOYEES");
                });

            modelBuilder.Entity("AssignmentAdminEmployees.Domain.Moduls.GENDER", b =>
                {
                    b.Property<decimal>("GENDER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GENDER_DESC")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("GENDER_ID");

                    b.ToTable("GENDER");
                });

            modelBuilder.Entity("AssignmentAdminEmployees.Domain.Moduls.RECOREDSTATUS", b =>
                {
                    b.Property<decimal>("RECORED_STATUS_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RECORED_STATUS_DESC")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RECORED_STATUS_ID");

                    b.ToTable("RECOREDSTATUS");
                });

            modelBuilder.Entity("AssignmentAdminEmployees.Domain.Moduls.STATUS", b =>
                {
                    b.Property<decimal>("STATUS_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("STATUS_DESC")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("STATUS_ID");

                    b.ToTable("STATUS");
                });

            modelBuilder.Entity("AssignmentAdminEmployees.Domain.Moduls.User", b =>
                {
                    b.Property<decimal>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
